resources:
  - rbac.yaml
  - service.yaml
  - deployment.yaml
namespace: kserve

images:
  - name: kserve/models-web-app
    newName: localhost:32000/models-web-app
    newTag: dev
patches:
  - target:
      kind: Deployment
      name: kserve-models-web-application
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
      - op: replace
        path: /spec/template/spec/securityContext/runAsNonRoot
        value: false
      - op: remove
        path: /spec/template/spec/containers/0/securityContext/runAsUser
configMapGenerator:
  - literals:
      - APP_DISABLE_AUTH="True"
      - APP_PREFIX=/
      - APP_SECURE_COOKIES="False"
    name: kserve-models-web-application-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: kserve-models-web-application
      kustomize.component: kserve-models-web-application
