# It extends the default conf by adjusting some options.
extends: default

rules:
  document-start:
    present: false
  document-end:
    present: false
  indentation:
    indent-sequences: consistent
  line-length:
    max: 400
  truthy:
    allowed-values: ["on", "off", "true", "false"]
  empty-lines:
    level: warning
